### ISSUE TITLE
Error: Failed to install 'unknown package' from GitHub:   Line starting 'covering amphibian,  ...' is malformed!

### ISSUE THREAD

**Issue by sahmoli** [RS-eco/traitdata#1]
I just followed your instruction to install traitdata in R, and I got the following error message:

Error: Failed to install 'unknown package' from GitHub:
  Line starting 'covering amphibian,  ...' is malformed!

**Comment by RS-eco** [comment]
Sorry for the delay in replying, I only now saw that you posted an issue. 
There was an error in the amphi_lifehist dataset, which should now be resolved.
Can you please check if it works for you now.
