### ISSUE TITLE
Error when trying to install

### ISSUE THREAD

**Issue by TravisGallo** [RS-eco/traitdata#2]
Using R 4.2.2 on a Mac I get the following error when trying to install form GitHub.

_Error: Failed to install 'traitdata' from GitHub:
  ! System command 'R' failed_

When trying to install from CRAN I get the following error:

_Warning in install.packages :
  package ‘traitdata’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages_

**Comment by RS-eco** [comment]
Have you installed any package from Github in the past? I am not familiar with installing R packages from Github on Mac, so am not sure what is going wrong here.
Regarding installation from CRAN, the package is only available from Github and not from CRAN, so this won't work for sure.

**Comment by TravisGallo** [comment]
I changed the `build_vignette` argument to false and it worked. Perhaps there is an issue with building vignettes argument with R 4.2.2. I also ran it with the `force` argument being true and false and it worked either way. So, the issue seems to be with the `build_vignette` argument.
